name: setLastUpdatedOn
on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:

jobs:
  get-verse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setting Template File
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "ranjeetrocky"
          git config --global user.email "ranjeetrocky2000@gmail.com"
          git commit -m "[Automated] README updated!"
      - name: Push
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
